

query = """
,1,E,'Hero Sushi' 'Hero Sushi'),
,1,E,'Top Notch' 'Top Notch'),
,1,E,'EG GROUP' 'EG Group'),
,1,E,'BELONG' 'Belong'),
,1,E,'Belong' 'Belong'),
,1,E,'MCDONALDS' 'McDonalds'),
,1,E,'GOLD LEAF' 'Gold Leaf'),
,1,E,'CRUNCHYROLL' 'Crunchyroll'),
,1,E,'UBER' 'Uber'),
,1,E,'SPOTIFY' 'Spotify'),
,1,E,'NoodleBox' 'Noodlebox'),
,1,E,'Mighty Moonee Ponds' 'Mighty Moonee Ponds'),
,1,E,'Zeus Street Greek' 'Zeus Street Greek'),
,1,E,'SUPA IGA' 'IGA'),
,1,E,'COLES EXPRESS' 'Coles Express'),
,1,E,'OPTUS' 'Optus'),
,1,E,'EASTLINK' 'Eastlink'),
,1,E,'ENERGYAUSTRALIA' 'EnergyAustralia'),
,1,E,'TANGO' 'Tango Energy'),
,1,E,'JB HI-FI' 'JB Hi-Fi'),
,1,E,'WOOLWORTHS' 'Woolworths'),
,1,E,'MYKI' 'Myki'),
,1,E,'Sir Duke' 'Sir Duke'),
,1,E,'7-ELEVEN' '7-Eleven'),
,1,E,'HUNKY DORY' 'Hunky Dory'),
,1,E,'KMART' 'Kmart'),
,1,E,'CHEM WAREHS' 'Chemist Warehouse'),
,1,E,'CHEMIST WAREHOUSE' 'Chemist Warehouse'),
,1,E,'HEALTHY PETS' 'Healthy Pets'),
,1,E,'ALLISON BROWNING' 'Allison Browning'),
,1,E,'COMMONWEALTH INSURANCE' 'Commonwealth Insurance'),
,1,E,'BUNNINGS' 'Bunnings'),
,1,E,'Yarra Valley Water' 'Yarra Valley Water'),
,1,E,'KFC' 'KFC'),
,1,E,'XERO' 'Xero'),
,1,E,'DR BILGE' 'Dr Bilge'),
,1,E,'SPOTLIGHT' 'Spotlight'),
,1,E,'ALLIANZ' 'Allianz'),
,1,E,'MasterCardPayment' 'Mastercard Payment'),
,1,E,'RACV' 'RACV'),
,1,E,'ALDI' 'ALDI'),
,1,E,'Hungry Jacks' 'Hungry Jacks'),
,1,E,'Home Loan' 'Home Loan'),
,1,E,r'(Loan Repayment' 'Home Loan'),
,1,E,'AIA AUSTRALIA' 'AIA Australia'),
,1,E,'Fast Transfer From Everkeen)': 'Everkeen'),
,1,E,'CBA CR CARD AUTOPAY' 'Mastercard Autopay'),
,1,E,'AUTO PAYMENT - THANK YOU' 'Mastercard Autopay'),
,1,E,'Uniqlo' 'Uniqlo)'
        """
       
i = 0
for line in query.splitlines():
    print("(" + str(i) + line)
    i = i + 1




query = """
INSERT INTO mapping_table(id, audit_id, income_expense, map_from, map_to)
VALUES
(1,1,'E','Hero Sushi','Hero Sushi'),
(2,1,'E','Top Notch','Top Notch'),
(3,1,'E','EG GROUP','EG Group'),
(4,1,'E','BELONG','Belong'),
(5,1,'E','Belong','Belong'),
(6,1,'E','MCDONALDS','McDonalds'),
(7,1,'E','GOLD LEAF','Gold Leaf'),
(8,1,'E','CRUNCHYROLL','Crunchyroll'),
(9,1,'E','UBER','Uber'),
(10,1,'E','SPOTIFY','Spotify'),
(11,1,'E','NoodleBox','Noodlebox'),
(12,1,'E','Mighty Moonee Ponds','Mighty Moonee Ponds'),
(13,1,'E','Zeus Street Greek','Zeus Street Greek'),
(14,1,'E','SUPA IGA','IGA'),
(15,1,'E','COLES EXPRESS','Coles Express'),
(16,1,'E','OPTUS','Optus'),
(17,1,'E','EASTLINK','Eastlink'),
(18,1,'E','ENERGYAUSTRALIA','EnergyAustralia'),
(19,1,'E','TANGO','Tango Energy'),
(20,1,'E','JB HI-FI','JB Hi-Fi'),
(21,1,'E','WOOLWORTHS','Woolworths'),
(22,1,'E','MYKI','Myki'),
(23,1,'E','Sir Duke','Sir Duke'),
(24,1,'E','7-ELEVEN','7-Eleven'),
(25,1,'E','HUNKY DORY','Hunky Dory'),
(26,1,'E','KMART','Kmart'),
(27,1,'E','CHEM WAREHS','Chemist Warehouse'),
(28,1,'E','CHEMIST WAREHOUSE','Chemist Warehouse'),
(29,1,'E','HEALTHY PETS','Healthy Pets'),
(30,1,'E','ALLISON BROWNING','Allison Browning'),
(31,1,'E','COMMONWEALTH INSURANCE','Commonwealth Insurance'),
(32,1,'E','BUNNINGS','Bunnings'),
(33,1,'E','Yarra Valley Water','Yarra Valley Water'),
(34,1,'E','KFC','KFC'),
(35,1,'E','XERO','Xero'),
(36,1,'E','DR BILGE','Dr Bilge'),
(37,1,'E','SPOTLIGHT','Spotlight'),
(38,1,'E','ALLIANZ','Allianz'),
(39,1,'E','MasterCardPayment','Mastercard Payment'),
(40,1,'E','RACV','RACV'),
(41,1,'E','ALDI','ALDI'),
(42,1,'E','Hungry Jacks','Hungry Jacks'),
(43,1,'E','Home Loan','Home Loan'),
(44,1,'E','Loan Repayment','Home Loan'),
(45,1,'E','AIA AUSTRALIA','AIA Australia'),
(46,1,'E','Fast Transfer From Everkeen','Everkeen'),
(47,1,'E','CBA CR CARD AUTOPAY','Mastercard Autopay'),
(48,1,'E','AUTO PAYMENT - THANK YOU','Mastercard Autopay'),
(49,1,'E','Uniqlo','Uniqlo')
        """

